name: language_pickers
description: It makes language select pickers for you in Flutter. You can use it freely in lots of ways.
version: 0.1.2
author: Gomgom <dev@gomgom.io>
homepage: https://github.com/gomgomize/flutter_language_pickers

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#  assets:
#  - assets/
